### ISSUE TITLE
build-valuelist-comp-with-another-csv

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/honey-badger#10]
Maybe I'm doing sth wrong, but I can't seem to build another valuelist component with another csv. It tells me, it can't find "planets.csv". See this branch: https://github.com/architecture-building-systems/hive/tree/111-Database-SIA-2024-and-2028
```
C:\Program Files\IronPython 2.7>ipy.exe c:\Users\chwaibel\Documents\GitHub\honey-badger\honey-badger.py c:\Users\chwaibel\Documents\GitHub\hive\Core\sia380\sia2024.json
Traceback (most recent call last):
  File "c:\Users\chwaibel\Documents\GitHub\honey-badger\honey-badger.py", line 67, in main
    parameter_compiler.compile_parameters(
  File "c:\Users\chwaibel\Documents\GitHub\honey-badger\parameter_compiler.py", line 46, in compile_parameters
    keys, values = read_values(badger_dir, parameter["csv"])
  File "c:\Users\chwaibel\Documents\GitHub\honey-badger\parameter_compiler.py", line 123, in read_values
    with open(os.path.join(badger_dir, "planets.csv")) as planets:
IOError: [Errno 2] Could not find file 'c:\Users\chwaibel\Documents\GitHub\hive\Core\sia380\planets.csv'.: c:\Users\chwaibel\Documents\GitHub\hive\Core\sia380\planets.csv
None
```

**Comment by daren-thomas** [comment]
@christophwaibel newest version of master should work now. NOTE: your csv file is formatted wrong. do you have the original Excel file so I can look at it?

problems:
- usage of ";" as delimiter - non-standard, but do-able, _as long as_ "sniffing" the dialect doesn't find any commas
- field names are really complicated. do you need that? you'll need to reference these in code...
- header line is split up into multiple lines - this could be a problem
- what is the encoding of this file?

**Comment by christophwaibel** [comment]
> @christophwaibel newest version of master should work now. NOTE: your csv file is formatted wrong. do you have the original Excel file so I can look at it?
> 
the excel is here: https://github.com/architecture-building-systems/hive/tree/master/Core/sia380
Yes agree, wrapping a sentence into "..." makes sense. Haven't thought of it

regarding the descriptions: those are from SIA2024. Thought, it would be good to keep them, so students can directly relate to them
