### ISSUE TITLE
cant-load-honeybadger-component

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/honey-badger#13]
pliz hepl @daren-thomas  
I'm here with my laptop. I installed Pycharm, ironpython 2.7, cloned honey-badger, built a .json with the cmd (`ipy.exe ...\honey-badger.py ...\component.json`), but when trying to open grasshopper, it gives me this error:

![image](https://user-images.githubusercontent.com/21927657/76170261-931bc400-6180-11ea-935e-f210e2f5eb42.png)

I did copy the honey-badger.dll into the rhino grasshopper components folder. 

Do you have an idea how I can fix that?

**Comment by daren-thomas** [comment]
@christophwaibel It's looking for a module `honey_badger_d9a3beb....` did you copy that too?

The easiest way to install it would be:

```
ipy.exe honey-badger.py -i badgerfile.json
```

notice the `-i`  - this will copy all the files to the right folder.

**Comment by christophwaibel** [comment]
@daren-thomas that's not it. all files are in the same folder with the ghpy

**Comment by christophwaibel** [comment]
@daren-thomas could you build a hive honey-badger component, `combustion.json` ideally, on your machine, and send me the `.ghpy` and the `hblib....py` and `honey_badger_586zghwih3etc...py` files? If those work, then the problem must be in building the components on my laptop.

**Comment by daren-thomas** [comment]
The problem seems to have been a version mismatch of IronPython - [release 2.7.8](https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.8) is the correct version - until Grasshopper changes its version: They should match.
